---
- name: Deploy AutoNet Infrastructure
  hosts: localhost
  connection: local
  gather_facts: false
  
  vars_files:
    - ansible/group_vars/all.yml
    
  vars:
    # Shared variable for both roles
    temp_config_path: "./temp_kube_config"

  tasks:
    - block:
        # Step 1: Prepare Environment (Decrypt & Check)
        - name: Run Common Setup
          import_role:
            name: ./ansible/roles/k8s_common_setup
        
        # Step 2: Deploy Application
        - name: Run AutoNet Deployment
          import_role:
            name: ./ansible/roles/autonet_deploy

      # Step 3: Cleanup (Runs even if Step 1 or 2 fails)
      always:
        - name: Remove Temporary Kubeconfig
          file:
            path: "{{ temp_config_path }}"
            state: absent